### PR TITLE
fix: stop making actions of initial renderer async

### LINKED ISSUE #254: Actions from main process not received on app start using preload script
At the first start of the application I'm writing the active user of the authentication cookie to the redux store. But when my app initially loaded the `activeUser` value is still `null` (the default value of the store in the main process). Only after a reload it is working fine.

What I have found out so far:
1. The main process is initialize with an empty `activeUser`
2. The preload is dispatching an action which will only be send to the main process
3. The main process is receiving the action and is changing the main store
4. The main process is sending back the action to the renderer
5. The renderer is **not** receiving the action via the `ipcRenderer.on()` listener
6. After a reload the renderer will receive the action

### Solution 1 (recommended)
One solution (and the best IMO) would be not to ignore the actions within the renderers, but to ignore them instead in the `forwardToRenderer` function because then you don't have to forward them from the main process back to the renderer that was originally the root of that action which will also speed up the app a little bit. To achieve this, it would be necessary to add an identifier to the renderers.

### Solution 2 (workaround)
The second solution would be to wait when the window is loaded and then send the event actions. The problem would be that this could easily lead to a slower UX and also to flickering of the ui during the first render, just in case you have exactly this problem.
https://github.com/klarna/electron-redux/blob/c6f8521cbc0c29a0efd9795486b477e40834d40e/packages/electron-redux/src/middleware/forwardToRenderer.js#L20
This line could be replaced with something similar to the following one:
```javascript
if (contents.isLoadingMainFrame()) {
  contents.on('did-finish-load', () => {
    contents.send('redux-action', rendererAction);
  });
} else {
  contents.send('redux-action', rendererAction);
}
```

**Desktop:**
 - OS: macOS Catalina 10.15.6
 - Version 1.5.4

### PR DESCRIPTION
**Pull request by sapkra**
Fixes #254 

The tests are still broken but it would be great to get some feedback if this approach is fine, before I fix them.
I will also add the new `id` option/param to the docs later.

A full explanation what my PR is doing you can in the linked issue.

### CODE REVIEW

**Comment by sapkra** [comment]
Using my fork with this fix in production for about a month and seems to work completely fine. Would be great to get feedback if this solution is ok like that or if we should search for another one.

**Comment by matmalkowski** [comment]
@sapkra Hey, sorry for getting back to you so late, 

As you might probably noticed, we started working on the v2 rewrite of the library, that includes also a bit of changes about how the logic itself is implemented & exposed. Your proposed solution in the issue about making the renderers identifiable and moving the filtering logic makes sense - so please take a look at the v2 code thats right now on the `alpha` branch and let us know if you could work on implementing this feature on the new code base :)

**Comment by sapkra** [comment]
I will have a look at it. Thank you for reaching out.

**Comment by sapkra** [comment]
@matmalkowski It's already implemented I guess. But with a more dynamic solution so that the user don't have to manually specify the ID anymore.

**Comment by sapkra** [comment]
@matmalkowski Ok, I found the problem why it not working. First of all the stuff I added in this PR is almost completely implemented in 2.0.0-alpha.1.

The problem is that the state change I'm doing in my preload script is faster than the `replaceState` action because it relies on an async callback from the main process. So my state is getting set and immediately reset.
It's a problem in the core concept of the rewrite, so currently I have no idea how to fix it in the new codebase.

```bash
Object
  payload: {activeUser: "ckerc42xh00100828ivf1l95s"}
  type: "auth/SET"

Object
  meta: {scope: "local"}
  payload: {activeUser: null}
  type: "electron-redux.REPLACE_STATE"
```

**Comment by matmalkowski** [comment]
@sapkra I was thinking about this, and I'm not sure what is the _right_ way to approach this problem, that seems hard to avoid, since state sync, due to making it even driven, is by nature asynchronous. We cannot wait and delay store creation, as the enhancer have to synchronous.

One way of going about this problem, that could be helpful for some (and maybe you) would be to expose a callbacks that can get executed once the store get synced for example. This way you would be able to dispatch your action to the store after it updated. Thoughts?

**Comment by sapkra** [comment]
The approach in v1 using `remote.getGlobal('getReduxState');` was working fine. The new async approach broke the code.

**Comment by matmalkowski** [comment]
@sapkra Yes, but I believe the `remote` module is disabled by default in electron v10 for security reasons - but there is another way of synchronous communication, that could fetch the state from renderer on demand: [ipcRenderer.sendSync](https://www.electronjs.org/docs/api/ipc-renderer#ipcrenderersendsyncchannel-args)

Maybe we could use that instead of `remove` solution from v1, and make it default (so we don't break the lib behaviour that much compared to v1) and have the async synchronisation as an opt-in option?

**Comment by sapkra** [comment]
@matmalkowski Yes true, the remote module is disabled by default but I think it's still safe to use it in the preload script. But I'm not 100% sure. But anyway, it seems like sendSync is the better solution. Is the async solution even necessary if it's not working completely right. What are the advantages of this option?

Another small related topic is that I'm having self containing javascript objects in my store which breaks when using JSON.stringify in this library but I don't know if it's even possible to sync such complex stores.

**Comment by matmalkowski** [comment]
@sapkra 

> Is the async solution even necessary if it's not working completely right. What are the advantages of this option?

I think it's still a nice thing to have, considering, that sync operation is a blocking one, and I can see how it might slow down the store initialisation when dealing with big / deep store. 

> Another small related topic is that I'm having self containing javascript objects in my store which breaks when using JSON.stringify in this library but I don't know if it's even possible to sync such complex stores.

This used to support by default custom Map & Set serialization, but I have removed it and made it opt in since its agains the redux design to store non-serializable data in the store. Please take a look at #272 where I removed it, would using this help?

**Comment by sapkra** [comment]
@matmalkowski 

> I think it's still a nice thing to have

Ok, I don't think it will help that much because most apps rely on an already initialized store anyway I think. It's you project and if it might helpful for someone it could be implemented.

> This used to support by default custom Map & Set serialization

Thank you, I will have a look it it.


I'm closing this PR because there is still the open issue and this PR has no change anymore which will contribute to this topic. Are you planning implement the sync logic?

**Comment by matmalkowski** [comment]
@sapkra Yes, I will create issue now for it, and maybe tackle it on the weekend 👍🏻

**Pull request closed without merging**
