### PR TITLE
Extract helper from triggerAlias middleware

### PR DESCRIPTION
**Pull request by KevinSjoberg**
There is no way to expand an aliased action without going through the
triggerAlias middleware. By extracting the logic into a helper we can
now expand an aliased action without going through the middleware.

### CODE REVIEW

**Comment by hardchor** [comment]
@KevinSjoberg Thanks for the contribution and sorry for the late reply!
Can you give me a use case for this? I'm just about to add some documentation.

**Comment by KevinSjoberg** [comment]
@hardchor we've used it mainly for testing purposes, allowing us to "unwrap" an aliased action. 🙂

**Comment by KevinSjoberg** [comment]
@hardchor are you still thinking about getting this merged?

**Comment by hardchor** [comment]
@KevinSjoberg Absolutely, and massive sorry for the long delay! Do you mind adding a short section to the docs?

**Comment by victorhqc** [comment]
Merging this, as it doesn't introduce any breaking change and improves the testing :) thank you @KevinSjoberg

**Comment by KevinSjoberg** [comment]
Thanks! Appreciate it.

**Pull request merged**
